<?php
declare(strict_types=1); // [MXAIR2026-ROLL]

ini_set('memory_limit', '512M'); // [MXAIR2026-ROLL]
ini_set('max_execution_time', '600'); // [MXAIR2026-ROLL]

$config = require __DIR__ . '/config.php'; // [MXAIR2026-ROLL]
require __DIR__ . '/auth.php'; // [MXAIR2026-ROLL]
requireAuth($config); // [MXAIR2026-ROLL]

$isCli = PHP_SAPI === 'cli'; // [MXAIR2026-ROLL]
$basePath = null; // [MXAIR2026-ROLL]
if ($isCli) { // [MXAIR2026-ROLL]
    if ($argc < 2) { // [MXAIR2026-ROLL]
        fwrite(STDERR, "Usage: php build_geojson.php <path-to-vatmex>\n"); // [MXAIR2026-ROLL]
        exit(1); // [MXAIR2026-ROLL]
    } // [MXAIR2026-ROLL]
    $basePath = rtrim($argv[1], '/'); // [MXAIR2026-ROLL]
} else { // [MXAIR2026-ROLL]
    header('Content-Type: application/json; charset=utf-8'); // [MXAIR2026-ROLL]
    $basePath = isset($_GET['path']) ? trim((string)$_GET['path']) : null; // [MXAIR2026-ROLL]
    if (!$basePath) { // [MXAIR2026-ROLL]
        $payload = json_decode((string)file_get_contents('php://input'), true); // [MXAIR2026-ROLL]
        if (is_array($payload) && !empty($payload['path'])) { // [MXAIR2026-ROLL]
            $basePath = trim((string)$payload['path']); // [MXAIR2026-ROLL]
        } // [MXAIR2026-ROLL]
    } // [MXAIR2026-ROLL]
} // [MXAIR2026-ROLL]

function respond(array $payload, int $status = 200): void // [MXAIR2026-ROLL]
{ // [MXAIR2026-ROLL]
    http_response_code($status); // [MXAIR2026-ROLL]
    echo json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES); // [MXAIR2026-ROLL]
    exit; // [MXAIR2026-ROLL]
} // [MXAIR2026-ROLL]

if (!$basePath || !is_dir($basePath)) { // [MXAIR2026-ROLL]
    if ($isCli) { // [MXAIR2026-ROLL]
        fwrite(STDERR, "Provided path does not exist: {$basePath}\n"); // [MXAIR2026-ROLL]
        exit(1); // [MXAIR2026-ROLL]
    } // [MXAIR2026-ROLL]
    respond(['error' => 'Provided path does not exist.', 'path' => $basePath], 400); // [MXAIR2026-ROLL]
} // [MXAIR2026-ROLL]

$script = __DIR__ . '/scripts/vatmex_to_geojson.php'; // [MXAIR2026-ROLL]
if (!is_file($script)) { // [MXAIR2026-ROLL]
    if ($isCli) { // [MXAIR2026-ROLL]
        fwrite(STDERR, "Script missing: {$script}\n"); // [MXAIR2026-ROLL]
        exit(1); // [MXAIR2026-ROLL]
    } // [MXAIR2026-ROLL]
    respond(['error' => 'Conversion script missing.', 'path' => $script], 500); // [MXAIR2026-ROLL]
} // [MXAIR2026-ROLL]

$command = sprintf( // [MXAIR2026-ROLL]
    '%s %s %s', // [MXAIR2026-ROLL]
    escapeshellcmd(PHP_BINARY), // [MXAIR2026-ROLL]
    escapeshellarg($script), // [MXAIR2026-ROLL]
    escapeshellarg($basePath) // [MXAIR2026-ROLL]
); // [MXAIR2026-ROLL]

$descriptorSpec = [ // [MXAIR2026-ROLL]
    1 => ['pipe', 'w'], // [MXAIR2026-ROLL]
    2 => ['pipe', 'w'], // [MXAIR2026-ROLL]
]; // [MXAIR2026-ROLL]
$process = proc_open($command, $descriptorSpec, $pipes); // [MXAIR2026-ROLL]
if (!is_resource($process)) { // [MXAIR2026-ROLL]
    if ($isCli) { // [MXAIR2026-ROLL]
        fwrite(STDERR, "Failed to start conversion process.\n"); // [MXAIR2026-ROLL]
        exit(1); // [MXAIR2026-ROLL]
    } // [MXAIR2026-ROLL]
    respond(['error' => 'Failed to start conversion process.'], 500); // [MXAIR2026-ROLL]
} // [MXAIR2026-ROLL]

$stdout = stream_get_contents($pipes[1]); // [MXAIR2026-ROLL]
$stderr = stream_get_contents($pipes[2]); // [MXAIR2026-ROLL]
fclose($pipes[1]); // [MXAIR2026-ROLL]
fclose($pipes[2]); // [MXAIR2026-ROLL]
$exitCode = proc_close($process); // [MXAIR2026-ROLL]

if ($isCli) { // [MXAIR2026-ROLL]
    echo $stdout; // [MXAIR2026-ROLL]
    if ($stderr) { // [MXAIR2026-ROLL]
        fwrite(STDERR, $stderr); // [MXAIR2026-ROLL]
    }
    exit($exitCode); // [MXAIR2026-ROLL]
} // [MXAIR2026-ROLL]

respond([ // [MXAIR2026-ROLL]
    'ok' => $exitCode === 0, // [MXAIR2026-ROLL]
    'exit_code' => $exitCode, // [MXAIR2026-ROLL]
    'stdout' => $stdout, // [MXAIR2026-ROLL]
    'stderr' => $stderr, // [MXAIR2026-ROLL]
    'path' => $basePath, // [MXAIR2026-ROLL]
]);
